// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = 'https://grxaajpzwsmtpuewquag.supabase.co';
const SUPABASE_ANON_KEY = 'eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImdyeGFhanB6d3NtdHB1ZXd1YWciLCJyb2xlIjoiYW5vbiIsImlhdCI6MTczNjE1NjQxNSwiZXhwIjoyMDUxNzMyNDE1fQ.8M8L5vHjnJzRZkK-3j8oJ9kKJgqJ3s8dH9nN8nH8n8';

if (!SUPABASE_URL || !SUPABASE_ANON_KEY) {
  console.warn('Using placeholder Supabase credentials. Set VITE_SUPABASE_URL and VITE_SUPABASE_ANON_KEY in .env for full functionality.');
}

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_ANON_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});